---
- name: "Install rcron"
  copy: >
    src=rcron.py
    dest=/bin/rcron
    owner=root
    group=root
    mode=0755

- name: "Make rcron etc directory"
  file: >
    path=/etc/rcron
    owner=root
    group=root
    state=directory

- name: "Create rcron config"
  copy: >
    src=rcron.conf.example
    dest=/etc/rcron/rcron.conf
    owner=root
    group=root
    mode=0644

- name: "Install rcron init script"
  copy: >
    src=debian.initd.sh
    dest=/etc/init.d/rcron
    owner=root
    group=root
    mode=0755

- name: "Log every reboot (through rcron)"
  cron: >
    name="rcron reboot"
    job="/bin/rcron echo Ran at $(date) >> /tmp/rcron.log"

- name: "Run every minute (through rcron)"
  cron: >
    name="rcron minutely"
    special_time=reboot
    job="/bin/rcron echo Rebooted at $(date) >> /tmp/rcron.log"
